# Generated by Django 5.1.7 on 2025-06-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
